"""
Django settings for familytree project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_list(name, default=''):
    return [v.strip() for v in os.environ.get(name, default).split(',') if v.strip()]


# ==== Орчны хувьсагчаас (env) — production-д docker-compose дамжуулна ====
# Локал dev-д env байхгүй бол доорх default-ууд хэвээр ажиллана.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-egs@h94s8wsx8$u#^qu7&@%_&kweyn@h!s!08zc7y=#s-ow8af',
)

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', '*') or ['*']

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS') or [
    'https://haltariinhan.aidolab.mn',
    'https://www.haltariinhan.aidolab.mn',
    'http://192.168.1.40:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'tree',
]

# username = утасны дугаар, password = төрсөн он-сар-өдөр
AUTHENTICATION_BACKENDS = [
    'tree.auth_backend.PhoneBirthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/newtreh/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'familytree.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'familytree.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# POSTGRES_DB тохируулсан бол PostgreSQL (production, өгөгдөл хадгалагдана),
# эс бөгөөс локал dev-д sqlite ашиглана.
if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'db'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'mn'

TIME_ZONE = 'Asia/Ulaanbaatar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # collectstatic → nginx үүнийг үзүүлнэ

# HTTPS-ийн ард (nginx) ажиллах үед
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Uploaded media — AWS_S3_BUCKET тохируулсан бол S3 руу (хүн бүрийн профайл/цомгийн
# зургийг тусдаа хавтаст оруулдаг, tree/storage.py), эс бөгөөс локал диск (dev).
# MEDIA_ROOT-г S3 идэвхтэй үед ч тодорхойлсон хэвээр байлгана — хуучин (S3-руу шилжихээс
# өмнөх) локал файлуудыг унших/шилжүүлэхэд (migrate_media_to_s3 command) хэрэгтэй.
MEDIA_ROOT = BASE_DIR / 'media'
AWS_S3_BUCKET = os.environ.get('AWS_S3_BUCKET', '')

if AWS_S3_BUCKET:
    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
    AWS_STORAGE_BUCKET_NAME = AWS_S3_BUCKET
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ap-northeast-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_DEFAULT_ACL = None          # bucket policy аль хэдийн public-read (ACL шаардахгүй)
    AWS_QUERYSTRING_AUTH = False    # нийтийн (public) URL — гарын үсэггүй, S3 CORS-той ажиллана
    AWS_S3_FILE_OVERWRITE = False   # ижил нэртэй зураг байвал давхардуулахгүй санамсаргүй дугаар нэмнэ
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
else:
    MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
