# Generated by Django 4.2.30 on 2026-07-11 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Нэр')),
                ('gender', models.CharField(choices=[('m', 'Эрэгтэй'), ('f', 'Эмэгтэй')], default='m', max_length=1, verbose_name='Хүйс')),
                ('gen', models.PositiveSmallIntegerField(default=1, verbose_name='Үе')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Хочит / үүрэг')),
                ('birth', models.CharField(blank=True, max_length=40, verbose_name='Төрсөн')),
                ('death', models.CharField(blank=True, max_length=40, verbose_name='Өөд болсон')),
                ('spouse', models.CharField(blank=True, max_length=300, verbose_name='Гэр бүл (нөхөр/эхнэр)')),
                ('bio', models.TextField(blank=True, verbose_name='Намтар')),
                ('phone', models.CharField(blank=True, help_text='Нэвтрэх нэр (username) болно.', max_length=30, verbose_name='Утас')),
                ('social', models.CharField(blank=True, help_text='Facebook / Instagram / и-мэйл г.м.', max_length=300, verbose_name='Сошиал хаяг')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Гэрийн хаяг')),
                ('family_photo', models.ImageField(blank=True, null=True, upload_to='family_photos/', verbose_name='Гэр бүлийн зураг')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ах дүүсийн дунд эрэмбэлэх дугаар.', verbose_name='Эрэмбэ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree.person', verbose_name='Эцэг/эх')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хүн',
                'verbose_name_plural': 'Хүмүүс',
                'ordering': ['gen', 'order', 'id'],
            },
        ),
    ]
