# Generated by Django 4.2.30 on 2026-07-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Нэр')),
                ('gender', models.CharField(choices=[('m', 'Эрэгтэй'), ('f', 'Эмэгтэй')], default='f', max_length=1, verbose_name='Хүйс')),
                ('birth', models.CharField(blank=True, max_length=40, verbose_name='Төрсөн')),
                ('death', models.CharField(blank=True, max_length=40, verbose_name='Өөд болсон')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Утас')),
                ('social', models.CharField(blank=True, max_length=300, verbose_name='Сошиал хаяг')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Гэрийн хаяг')),
                ('bio', models.TextField(blank=True, verbose_name='Намтар')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spouse_photos/', verbose_name='Хувийн зураг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Эрэмбэ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_details', to='tree.person', verbose_name='Гэр бүлийн гишүүн')),
            ],
            options={
                'verbose_name': 'Хань (нөхөр/эхнэр)',
                'verbose_name_plural': 'Хань (нөхөр/эхнэр)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
