# Generated by Django 4.2.30 on 2026-07-11 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_spouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('birth', 'Шинэ гишүүн'), ('spouse', 'Гэр бүл'), ('edit', 'Мэдээлэл шинэчлэл')], default='birth', max_length=20, verbose_name='Төрөл')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('body', models.CharField(blank=True, max_length=400, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Огноо')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tree.person', verbose_name='Холбоотой хүн')),
            ],
            options={
                'verbose_name': 'Мэдэгдэл',
                'verbose_name_plural': 'Мэдэгдэл',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
