# Generated by Django 4.2.30 on 2026-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Модон дээрх дугуй зураг (thumbnail) болно.', null=True, upload_to='person_photos/', verbose_name='Хувийн зураг'),
        ),
    ]
