# Generated by Django 4.2.30 on 2026-07-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_load_full_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('urgiin_bayar', 'Ургийн баяр'), ('tsagaan_sar', 'Цагаан сар'), ('other', 'Бусад')], default='urgiin_bayar', max_length=20, verbose_name='Төрөл')),
                ('year', models.PositiveIntegerField(verbose_name='Он')),
                ('title', models.CharField(blank=True, help_text='Хоосон бол «Төрөл · Он» гэж автоматаар харагдана.', max_length=200, verbose_name='Гарчиг')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('date', models.CharField(blank=True, help_text='Ж: «2024.02.10» эсвэл «Хаврын дунд сар».', max_length=60, verbose_name='Огноо')),
            ],
            options={
                'verbose_name': 'Баяр / үйл явдал',
                'verbose_name_plural': 'Баяр / үйл явдал',
                'ordering': ['-year', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Зураг'), ('video', 'Видео')], default='photo', max_length=10, verbose_name='Төрөл')),
                ('url', models.URLField(help_text='S3 дээрх зураг/видеоны нийтийн (public) URL.', max_length=600, verbose_name='S3 URL')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Видеоны хувьд урьдчилан харах зураг (заавал биш).', max_length=600, verbose_name='Видеоны poster (thumbnail) URL')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Тайлбар')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Эрэмбэ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tree.event', verbose_name='Үйл явдал')),
            ],
            options={
                'verbose_name': 'Зураг / видео',
                'verbose_name_plural': 'Зураг / видео',
                'ordering': ['order', 'id'],
            },
        ),
    ]
