# Generated by Django 4.2.30 on 2026-07-16 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_event_eventmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='album/', verbose_name='Зураг')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Тайлбар')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Нэмсэн огноо')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='tree.person', verbose_name='Хүн')),
            ],
            options={
                'verbose_name': 'Цомгийн зураг',
                'verbose_name_plural': 'Зургийн цомог',
                'ordering': ['order', '-created_at', 'id'],
            },
        ),
    ]
