# Generated by Django 4.2.30 on 2026-07-16 14:34

from django.db import migrations, models
import tree.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_load_full_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_photo',
            field=models.ImageField(blank=True, null=True, upload_to=tree.storage.person_family_photo_path, verbose_name='Гэр бүлийн зураг'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Модон дээрх дугуй зураг (thumbnail) болно.', null=True, upload_to=tree.storage.person_photo_path, verbose_name='Хувийн зураг'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='image',
            field=models.ImageField(upload_to=tree.storage.person_album_path, verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=tree.storage.spouse_photo_path, verbose_name='Хувийн зураг'),
        ),
    ]
