# Generated by Django 4.2.30 on 2026-07-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_alter_person_family_photo_alter_person_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='video_poster',
            field=models.URLField(blank=True, max_length=600, verbose_name='Видеоны poster зураг URL'),
        ),
        migrations.AddField(
            model_name='notification',
            name='video_url',
            field=models.URLField(blank=True, help_text='S3 дээрх видеоны нийтийн (public) URL. Бөглөвөл дарахад lightbox-оор тоглуулна.', max_length=600, verbose_name='Видео URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('birth', 'Шинэ гишүүн'), ('spouse', 'Гэр бүл'), ('edit', 'Мэдээлэл шинэчлэл'), ('video', 'Видео')], default='birth', max_length=20, verbose_name='Төрөл'),
        ),
    ]
